---
- name: install and config java tomcat
  hosts: webservers
  gather_facts: false 
  tasks:
    - name: Updating repos
      yum:
         name: "*"
         state: latest
    - name: Installing required java 
      yum:
        name: java-1.8.0-openjdf
        state: latest
    - name: Download required tomcat
      get_url:
          url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.46/bin/apache-tomcat-9.0.46.tar.gz
          dest: /usr/local    